import { AlertTriangle, CheckCircle2, Clock3, FileClock, FileWarning, ShieldAlert, TrendingUp } from "lucide-react";
import { useEffect, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useCases } from "@/lib/sentinel.hooks";
import { CaseTable } from "./case-table";
import { Page, Panel, SectionHeader } from "./shared";
const metrics=[["Active Investigations","24","+3 today",ShieldAlert,"text-info"],["Awaiting Approval","7","$84.2K exposure",Clock3,"text-warning"],["High Risk","11","≥ 80% probability",AlertTriangle,"text-critical"],["Evidence Requests","5","2 overdue",FileClock,"text-warning"],["Closed Cases","128","This month",CheckCircle2,"text-success"],["SAR Required","3","1 pending review",FileWarning,"text-ai"]] as const;
const risk=[{name:"Low",value:18},{name:"Guarded",value:27},{name:"Elevated",value:39},{name:"High",value:24},{name:"Critical",value:11}];
const trend=[{t:"08:00",v:14},{t:"10:00",v:22},{t:"12:00",v:18},{t:"14:00",v:31},{t:"16:00",v:24}];
export function Dashboard(){
  const { data: cases } = useCases();
  const [hydrated, setHydrated] = useState(false);
  useEffect(() => setHydrated(true), []);
  const casesLength = hydrated ? cases?.length ?? 0 : 0;
  return <Page><SectionHeader title="Fraud Operations" description="Live investigation posture across the current queue" action={<div className="flex items-center gap-2 text-xs text-muted-foreground"><span className="status-pulse size-2 rounded-full bg-success"/>Updated 12 seconds ago</div>}/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{metrics.map(([label,value,note,Icon,color])=><Panel key={label} className="p-4"><div className="flex items-center justify-between"><Icon className={`size-4 ${color}`}/><TrendingUp className="size-3 text-muted-foreground"/></div><div className="mt-5 font-mono text-2xl font-semibold">{value}</div><div className="mt-1 text-[11px] font-medium">{label}</div><div className="mt-1 text-[10px] text-muted-foreground">{note}</div></Panel>)}</div><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_1fr]"><Panel className="p-4"><div className="mb-4 text-xs font-semibold">Risk distribution</div><div className="h-48"><ResponsiveContainer width="100%" height="100%"><BarChart data={risk}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="name" tick={{fill:"var(--muted-foreground)",fontSize:10}} axisLine={false}/><YAxis tick={{fill:"var(--muted-foreground)",fontSize:10}} axisLine={false}/><Tooltip contentStyle={{background:"var(--popover)",border:"1px solid var(--border)",fontSize:11}}/><Bar dataKey="value" fill="var(--info)" radius={[2,2,0,0]}/></BarChart></ResponsiveContainer></div></Panel><Panel className="p-4"><div className="mb-4 text-xs font-semibold">Investigation volume</div><div className="h-48"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="t" tick={{fill:"var(--muted-foreground)",fontSize:10}} axisLine={false}/><YAxis tick={{fill:"var(--muted-foreground)",fontSize:10}} axisLine={false}/><Tooltip contentStyle={{background:"var(--popover)",border:"1px solid var(--border)",fontSize:11}}/><Area type="monotone" dataKey="v" stroke="var(--info)" fill="var(--info-muted)"/></AreaChart></ResponsiveContainer></div></Panel></div><Panel className="mt-4 overflow-hidden"><div className="flex items-center justify-between border-b border-border p-4"><div><div className="text-xs font-semibold">Active investigations</div><div className="mt-1 text-[10px] text-muted-foreground">Highest priority cases requiring analyst attention</div></div><span className="font-mono text-xs text-muted-foreground">{casesLength} visible</span></div><CaseTable compact/></Panel></Page>}
