import { useCallback, useState } from "react";
import { Background, Controls, Handle, MiniMap, Position, ReactFlow, useEdgesState, useNodesState, type Node, type NodeProps } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { CreditCard, Mail, MapPin, Network, Receipt, UserRound } from "lucide-react";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { cn } from "@/lib/utils";
const kinds={customer:{icon:UserRound,tone:"border-info text-info"},card:{icon:CreditCard,tone:"border-warning text-warning"},transaction:{icon:Receipt,tone:"border-critical text-critical"},device:{icon:Network,tone:"border-ai text-ai"},email:{icon:Mail,tone:"border-success text-success"},region:{icon:MapPin,tone:"border-muted-foreground text-muted-foreground"}};
type GraphData={label:string;kind:keyof typeof kinds;detail:string};
function EntityNode({data}:NodeProps<Node<GraphData>>){const k=kinds[data.kind];const Icon=k.icon;return <div className={cn("min-w-32 rounded border bg-panel-raised px-3 py-2 shadow-lg",k.tone)}><Handle type="target" position={Position.Left}/><div className="flex items-center gap-2"><Icon className="size-3.5"/><span className="text-[9px] uppercase text-muted-foreground">{data.kind}</span></div><div className="mt-1 font-mono text-[10px] text-foreground">{data.label}</div><Handle type="source" position={Position.Right}/></div>}
const initialNodes:Node<GraphData>[]=[
{id:"customer",type:"entity",position:{x:20,y:120},data:{label:"CUS-48129",kind:"customer",detail:"4 cards · 128 transactions · risk history stable"}},
{id:"card",type:"entity",position:{x:210,y:120},data:{label:"CARD-9241",kind:"card",detail:"Baseline median $184 · first seen 2024-03-12"}},
{id:"txn",type:"entity",position:{x:410,y:40},data:{label:"TXN-908174",kind:"transaction",detail:"$8,920 · Digital · 10:38 UTC · risk 0.82"}},
{id:"device",type:"entity",position:{x:410,y:200},data:{label:"DEV-72A",kind:"device",detail:"First seen today · linked to 3 fraud cases"}},
{id:"email",type:"entity",position:{x:610,y:25},data:{label:"m•••@mail.com",kind:"email",detail:"Account age 14 days · one linked identity"}},
{id:"region",type:"entity",position:{x:610,y:200},data:{label:"REG-NL-04",kind:"region",detail:"Outside customer baseline region"}},
];
const initialEdges=[{id:"e1",source:"customer",target:"card",label:"OWNS"},{id:"e2",source:"card",target:"txn",label:"MADE"},{id:"e3",source:"txn",target:"device",label:"FROM_DEVICE"},{id:"e4",source:"txn",target:"email",label:"PURCHASER_EMAIL"},{id:"e5",source:"txn",target:"region",label:"BILLED_IN"},{id:"e6",source:"device",target:"region",label:"CONNECTED_TO"}].map(e=>({...e,animated:e.id==="e3",style:{stroke:"var(--muted-foreground)"},labelStyle:{fill:"var(--muted-foreground)",fontSize:8}}));
export function InvestigationGraph(){const [nodes,,onNodesChange]=useNodesState(initialNodes);const [edges,,onEdgesChange]=useEdgesState(initialEdges);const [selected,setSelected]=useState<GraphData>();const onClick=useCallback((_:unknown,node:Node<GraphData>)=>setSelected(node.data),[]);return <div className="relative h-[390px] overflow-hidden rounded bg-background subtle-grid"><ReactFlow nodes={nodes} edges={edges} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} nodeTypes={{entity:EntityNode}} onNodeClick={onClick} fitView minZoom={.5} maxZoom={1.8} proOptions={{hideAttribution:true}}><Background color="var(--border)" gap={24}/><Controls position="top-right"/><MiniMap position="bottom-right" pannable zoomable nodeColor="var(--info-muted)" maskColor="color-mix(in oklab, var(--background) 75%, transparent)"/></ReactFlow><Sheet open={!!selected} onOpenChange={v=>{if(!v)setSelected(undefined)}}><SheetContent className="border-border bg-panel"><SheetHeader><SheetTitle className="font-mono">{selected?.label}</SheetTitle><SheetDescription className="capitalize">{selected?.kind} entity</SheetDescription></SheetHeader><div className="mt-6 space-y-5"><div><div className="text-[10px] uppercase tracking-[0.1em] text-muted-foreground">Entity summary</div><p className="mt-2 text-sm leading-6">{selected?.detail}</p></div><div className="grid grid-cols-2 gap-3">{[["Related cases","3"],["Risk links","4"],["First observed","Today"],["Confidence","High"]].map(([k,v])=><div key={k} className="rounded border border-border bg-background p-3"><div className="text-[10px] text-muted-foreground">{k}</div><div className="mt-1 font-mono text-xs">{v}</div></div>)}</div></div></SheetContent></Sheet></div>}
