import { useState } from "react";
import { Activity, AlertTriangle, Check, CircleCheck, Clock3, FileSearch, HeartPulse, Search, Server, ShieldCheck, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { cases, memoryCases } from "@/lib/sentinel.mock";
import { ApprovalBadge, Page, Panel, Risk, SectionHeader, StatusBadge } from "./shared";
import { MemoryTable, SarDocument } from "./investigation";

export function Approvals(){const [tab,setTab]=useState("All");const [done,setDone]=useState<string[]>([]);const items=cases.filter(c=>c.status==="Awaiting Approval"||c.probability>.75);return <Page><SectionHeader title="Approval Inbox" description="Policy-gated actions awaiting accountable human review"/><Tabs value={tab} onValueChange={setTab}><TabsList className="mb-4 border border-border bg-panel">{["All","L1","L2","SAR","Completed"].map(t=><TabsTrigger key={t} value={t}>{t}</TabsTrigger>)}</TabsList></Tabs><div className="space-y-3">{items.filter(c=>tab==="All"||tab==="Completed"?true:c.id==="HHG-003"?tab==="L2":tab==="L1").map((c,i)=><Panel key={c.id} className="p-4"><div className="grid items-center gap-4 lg:grid-cols-[110px_160px_100px_110px_1fr_100px]"><div><div className="font-mono text-xs text-info">{c.id}</div><StatusBadge status={done.includes(c.id)?"Closed":c.status}/></div><div><div className="font-mono text-xs">{c.nextAction}</div><div className="text-[10px] text-muted-foreground">Policy R{3+i}</div></div><Risk value={c.probability}/><div className="font-mono text-xs text-critical">${c.exposure.toLocaleString()}</div><div className="text-xs text-muted-foreground">{c.verdict==="Fraud"?"Corroborated device links and customer denial":"High risk with incomplete customer intent evidence"}</div><ApprovalBadge route={i===0?"L2":"L1"}/></div><div className="mt-4 flex flex-wrap justify-end gap-2 border-t border-border pt-3">{done.includes(c.id)?<span className="flex items-center gap-2 text-xs text-success"><CircleCheck className="size-4"/>Decision recorded</span>:<><Button size="sm" variant="outline">View Investigation</Button><Button size="sm" variant="outline">Request More Evidence</Button><Button size="sm" variant="destructive" onClick={()=>setDone(x=>[...x,c.id])}><X/>Reject</Button><Button size="sm" variant="success" onClick={()=>setDone(x=>[...x,c.id])}><Check/>Approve</Button></>}</div></Panel>)}</div></Page>}
export function SarPage(){return <Page><SectionHeader title="SAR Reports" description="Review backend-generated suspicious activity reports before filing"/><SarDocument/></Page>}
export function MemoryPage(){return <Page><SectionHeader title="Case Memory" description="Retrieve prior investigations by outcome, pattern, entities, and similarity" action={<div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="h-9 w-72 pl-9 text-xs" placeholder="Search historical cases"/></div>}/><Panel className="mb-4 p-4"><div className="flex items-start gap-3"><div className="rounded bg-ai-muted p-2 text-ai"><FileSearch className="size-4"/></div><div><div className="text-xs font-semibold">Why these cases were retrieved for HHG-003</div><p className="mt-1 text-xs leading-5 text-muted-foreground">Entity overlap, first-seen device behavior, purchase channel, amount band, and customer-denial sequence contributed to similarity ranking.</p></div><div className="ml-auto font-mono text-xs text-ai">{memoryCases.length} matches</div></div></Panel><MemoryTable/></Page>}
const patterns=[
 ["Card testing","Rapid low-value authorizations followed by a larger attempt","Velocity · decline ratio · merchant spread","8","1,284","BLOCK_CARD"],
 ["CNP · new device","Digital purchase from a device absent from card history","First-seen device · atypical amount · email age","6","948","VERIFY_WITH_CUSTOMER"],
 ["Account takeover","Abrupt identity, device, and behavioral shift","Credential change · device change · payout activity","4","621","BLOCK_ACCOUNT"],
 ["Out-of-region use","Transaction outside established geographic baseline","Region novelty · travel velocity · device consistency","3","1,102","MONITOR_ACCOUNT"],
 ["Discovered pattern","Shared sparse device profiles across unrelated identities","Graph community · synchronized timing · email reuse","2","14","ESCALATE_TO_ANALYST"],
];
export function Patterns(){return <Page><SectionHeader title="Fraud Patterns" description="Known typologies and newly discovered graph behavior"/><div className="grid gap-3 lg:grid-cols-2">{patterns.map((p,i)=><Panel key={p[0]} className="p-4"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 text-sm font-semibold">{p[0]}{i===4&&<span className="rounded bg-ai-muted px-2 py-0.5 text-[9px] uppercase text-ai">Undocumented</span>}</div><p className="mt-2 text-xs text-muted-foreground">{p[1]}</p></div><AlertTriangle className={i===4?"size-4 text-ai":"size-4 text-warning"}/></div><div className="mt-4 rounded border border-border bg-background p-3"><div className="text-[10px] uppercase text-muted-foreground">Detection signals</div><div className="mt-1 text-xs">{p[2]}</div></div><div className="mt-4 grid grid-cols-3 gap-3 text-xs"><div><div className="text-[10px] text-muted-foreground">Active</div><div className="mt-1 font-mono">{p[3]}</div></div><div><div className="text-[10px] text-muted-foreground">Historical</div><div className="mt-1 font-mono">{p[4]}</div></div><div><div className="text-[10px] text-muted-foreground">Typical action</div><div className="mt-1 font-mono text-[10px]">{p[5]}</div></div></div></Panel>)}</div></Page>}
const matrix=[["ALLOW_TRANSACTION","Yes","—","—","—"],["BLOCK_TRANSACTION","—","Yes","Yes","—"],["BLOCK_CARD","—","—","Yes","Required"],["BLOCK_ACCOUNT","—","—","Yes","Required"],["MONITOR_ACCOUNT","Yes","—","—","—"],["WARN_CUSTOMER","Yes","—","—","—"],["FILE_REPORT","—","—","—","Required"],["REQUEST_EVIDENCE","Yes","—","—","—"]];
export function Policy(){return <Page><SectionHeader title="Policy & Rules" description="Deterministic action routing; recommendations do not bypass approval controls"/><div className="grid gap-4 xl:grid-cols-[320px_1fr]"><Panel className="p-4"><div className="mb-3 text-xs font-semibold">Active policy rules</div>{["R1 · Low-risk allow","R3 · Confirmed card fraud","R7 · Evidence sufficiency","R9 · SAR filing threshold","R10 · Human escalation"].map((r,i)=><div key={r} className="flex items-center gap-3 border-b border-border py-3 last:border-0"><ShieldCheck className={i>2?"size-4 text-warning":"size-4 text-success"}/><div><div className="text-xs">{r}</div><div className="mt-1 text-[10px] text-muted-foreground">Version 2.4 · Active</div></div></div>)}</Panel><Panel className="overflow-hidden"><div className="border-b border-border p-4 text-xs font-semibold">Action Permission Matrix</div><div className="overflow-x-auto"><div className="min-w-[640px]"><div className="grid grid-cols-[1.5fr_repeat(4,1fr)] border-b border-border bg-muted/30 px-4 py-2 text-[10px] uppercase text-muted-foreground"><span>Action</span><span>Auto</span><span>L1</span><span>L2</span><span>Human approval</span></div>{matrix.map(r=><div key={r[0]} className="grid grid-cols-[1.5fr_repeat(4,1fr)] border-b border-border px-4 py-3 text-xs last:border-0"><span className="font-mono">{r[0]}</span>{r.slice(1).map((v,i)=><span key={i} className={v==="Yes"?"font-semibold text-success":v==="Required"?"font-semibold text-critical":"text-muted-foreground"}>{v}</span>)}</div>)}</div></div></Panel></div></Page>}
const stages=["TRIGGER","SCOPE","EVIDENCE","ASSESS","REQUEST","REASSESS","DECIDE","POLICY","ACTION","EXPLAIN","MEMORY"];
const agentStats=[{label:"Current state",value:"POLICY",icon:Activity},{label:"Current tool",value:"evaluate_policy",icon:Server},{label:"Evidence retrieved",value:"9 items",icon:FileSearch},{label:"Probability",value:"0.89",icon:AlertTriangle}];
export function Agent(){return <Page><SectionHeader title="Agent Activity" description="Live investigation workflow and tool execution"/><Panel className="p-5"><div className="flex flex-wrap items-center gap-2">{stages.map((s,i)=><div key={s} className="flex items-center gap-2"><div className={"rounded border px-2 py-2 font-mono text-[9px] "+(i<7?"border-success/30 bg-success-muted text-success":i===7?"border-warning/40 bg-warning-muted text-warning status-pulse":"border-border text-muted-foreground")}>{s}</div>{i<stages.length-1&&<span className="text-muted-foreground">→</span>}</div>)}</div></Panel><div className="mt-4 grid gap-4 lg:grid-cols-4">{agentStats.map(item=>{const Icon=item.icon;return <Panel key={item.label} className="p-4"><Icon className="size-4 text-info"/><div className="mt-5 text-[10px] uppercase text-muted-foreground">{item.label}</div><div className="mt-1 font-mono text-sm">{item.value}</div></Panel>})}</div><Panel className="mt-4 p-4"><div className="mb-4 text-xs font-semibold">Live tool log</div>{[["10:46:09","evaluate_policy","R3 matched · route L2"],["10:46:03","receive_customer_response","denied=true"],["10:43:02","request_evidence","VERIFY_WITH_CUSTOMER"],["10:42:57","retrieve_similar_cases","12 cases retrieved"]].map(r=><div key={r[0]} className="grid grid-cols-[90px_220px_1fr] border-b border-border py-3 font-mono text-xs last:border-0"><span className="text-muted-foreground">{r[0]}</span><span className="text-info">{r[1]}</span><span>{r[2]}</span></div>)}</Panel></Page>}
export function SystemHealth(){const services=[["TigerGraph","Operational","34 ms"],["Agent","Operational","Active"],["Policy Engine","Operational","v2.4"],["GraphRAG","Operational","52 ms"],["Case Memory","Operational","99.98%"],["API","Degraded","184 ms"]];return <Page><SectionHeader title="System Health" description="Service availability and investigation dependency status"/><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{services.map(([name,status,metric])=><Panel key={name} className="p-4"><div className="flex items-center justify-between"><HeartPulse className={status==="Operational"?"size-4 text-success":"size-4 text-warning"}/><span className={status==="Operational"?"text-[10px] text-success":"text-[10px] text-warning"}>{status}</span></div><div className="mt-5 text-sm font-semibold">{name}</div><div className="mt-1 font-mono text-[10px] text-muted-foreground">{metric}</div></Panel>)}</div></Page>}
export function Settings(){return <Page><SectionHeader title="Settings" description="Analyst workspace and notification preferences"/><Panel className="max-w-3xl divide-y divide-border">{[["High-risk alerts","Notify when probability reaches 80% or higher"],["Approval assignments","Notify when an L1 or L2 decision is assigned"],["Evidence responses","Notify when requested evidence is returned"]].map(([a,b])=><div key={a} className="flex items-center justify-between p-4"><div><div className="text-xs font-medium">{a}</div><div className="mt-1 text-[11px] text-muted-foreground">{b}</div></div><input type="checkbox" defaultChecked className="size-4 accent-primary"/></div>)}</Panel></Page>}
