/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as SarRouteImport } from './routes/sar'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SystemRouteImport } from './routes/system'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesIdRouteImport } from './routes/cases.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SarRoute = SarRouteImport.update({
  id: '/sar',
  path: '/sar',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesRoute,
} as any)
const CasesIdRoute = CasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/agent': typeof AgentRoute
  '/approvals': typeof ApprovalsRoute
  '/cases': typeof CasesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/memory': typeof MemoryRoute
  '/patterns': typeof PatternsRoute
  '/policy': typeof PolicyRoute
  '/sar': typeof SarRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/cases/$id': typeof CasesIdRoute
  '/cases/': typeof CasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/agent': typeof AgentRoute
  '/approvals': typeof ApprovalsRoute
  '/dashboard': typeof DashboardRoute
  '/memory': typeof MemoryRoute
  '/patterns': typeof PatternsRoute
  '/policy': typeof PolicyRoute
  '/sar': typeof SarRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/cases/$id': typeof CasesIdRoute
  '/cases': typeof CasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/agent': typeof AgentRoute
  '/approvals': typeof ApprovalsRoute
  '/cases': typeof CasesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/memory': typeof MemoryRoute
  '/patterns': typeof PatternsRoute
  '/policy': typeof PolicyRoute
  '/sar': typeof SarRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/cases/$id': typeof CasesIdRoute
  '/cases/': typeof CasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/agent'
    | '/approvals'
    | '/cases'
    | '/dashboard'
    | '/memory'
    | '/patterns'
    | '/policy'
    | '/sar'
    | '/settings'
    | '/system'
    | '/cases/$id'
    | '/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/agent'
    | '/approvals'
    | '/dashboard'
    | '/memory'
    | '/patterns'
    | '/policy'
    | '/sar'
    | '/settings'
    | '/system'
    | '/cases/$id'
    | '/cases'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/agent'
    | '/approvals'
    | '/cases'
    | '/dashboard'
    | '/memory'
    | '/patterns'
    | '/policy'
    | '/sar'
    | '/settings'
    | '/system'
    | '/cases/$id'
    | '/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  AgentRoute: typeof AgentRoute
  ApprovalsRoute: typeof ApprovalsRoute
  CasesRoute: typeof CasesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  MemoryRoute: typeof MemoryRoute
  PatternsRoute: typeof PatternsRoute
  PolicyRoute: typeof PolicyRoute
  SarRoute: typeof SarRoute
  SettingsRoute: typeof SettingsRoute
  SystemRoute: typeof SystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sar': {
      id: '/sar'
      path: '/sar'
      fullPath: '/sar'
      preLoaderRoute: typeof SarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof CasesRoute
    }
    '/cases/$id': {
      id: '/cases/$id'
      path: '/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof CasesIdRouteImport
      parentRoute: typeof CasesRoute
    }
  }
}

interface CasesRouteChildren {
  CasesIdRoute: typeof CasesIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesIdRoute: CasesIdRoute,
  CasesIndexRoute: CasesIndexRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  AgentRoute: AgentRoute,
  ApprovalsRoute: ApprovalsRoute,
  CasesRoute: CasesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  MemoryRoute: MemoryRoute,
  PatternsRoute: PatternsRoute,
  PolicyRoute: PolicyRoute,
  SarRoute: SarRoute,
  SettingsRoute: SettingsRoute,
  SystemRoute: SystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
